// <auto-generated />
namespace ASP_Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ASP_Site : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ASP_Site));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211635394_ASP_Site"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
